### ISSUE TITLE
大佬，安装之后nas本机获得了直链下载速度（满速），但外网观仍然看是通过服务器转发的。求问是哪里出了问题。

### ISSUE THREAD

**Issue by skypapapa** [thsrite/MediaLinker#1]
大佬，安装之后nas本机获得了直链下载速度（满速），和之前不走反代的下载速度不一样，但外网观看仍然是通过服务器转发的。求问是哪里出了问题。

**Comment by thsrite** [comment]
有问题去readme里代码开发者仓库提，本项目只是封装
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月19日 12:54 ***@***.***> ***@***.***>主题[thsrite/MediaLinker] 大佬，安装之后nas本机获得了直链下载速度（满速），但外网观仍然看是通过服务器转发的。求问是哪里出了问题。 (Issue #1)
大佬，安装之后nas本机获得了直链下载速度（满速），和之前不走反代的下载速度不一样，但外网观看仍然是通过服务器转发的。求问是哪里出了问题。
