### ISSUE TITLE
unraid docker xml文件需要修改

### ISSUE THREAD

**Issue by Shattered217** [thsrite/MediaLinker#2]
在该[文件](https://github.com/thsrite/MediaLinker/blob/main/deploy/my-MediaLinker.xml)中，第16行`<Icon>http://192.168.31.103:9768/images/icon/Nginx_D.png</Icon>`为内网地址，用户无法打开导致unraid docker加载缓慢，推荐将图标上传至github并替换加速链接`https://mirror.ghproxy.com/https://raw.githubusercontent.com/xxx.ico`

**Comment by thsrite** [comment]
@Shattered217  发b站了？ 传播的越广 死的越快的道理希望你知道

**Comment by Shattered217** [comment]
> @Shattered217  发b站了？ 传播的越广 死的越快的道理希望你知道

对不起，已经全网删除，给大家造成麻烦，我表示诚挚的抱歉
